export const Products = [
  {
    id: 1,
    img: 'https://source.unsplash.com/LxVxPA1LOVM/1000x800',
    name: 'nike stealth',
    purchases: '83,696',
    released: 'April 7, 2017',
    mfg: 'London, United Kingdom',
    featured: 'Editorial, Fashion',
    material: 'Rubber',
    type: 'Lace',
    price: '1900.00',
  },
  {
    id: 2,
    img: 'https://source.unsplash.com/164_6wVEHfI/1000x800',
    name: 'nike free',
    purchases: '139,037',
    released: 'November 15, 2018',
    mfg: 'revolt, Copenhagen, Denmark',
    featured: 'Editorial, Wallpapers',
    material: 'Polythene',
    type: 'Velcro',
    price: '2500.00',
  },
  {
    id: 3,
    img: 'https://source.unsplash.com/s-gYAbQToXk/1000x800',
    name: 'Nike Black and White Basketball Shoe.',
    purchases: '775',
    released: 'November 14, 2020',
    mfg: 'NA',
    featured: 'NA',
    material: 'Rubber',
    type: 'Velcro',
    price: '2500.00',
  },
  {
    id: 4,
    img: 'https://source.unsplash.com/v13tnV6D9lw/1000x800',
    name: 'Nike AirJordan 1',
    purchases: '4,052',
    released: 'November 14, 2018',
    mfg: 'Lisboa, Portugal',
    featured: 'Editorial, Health & Wellness',
    material: 'Rubber',
    type: 'Velcro',
    price: '2500.00',
  },
  {
    id: 5,
    img: 'https://source.unsplash.com/SxAXphIPWeg/1000x800',
    name: 'leather on concrete',
    purchases: '50,393',
    released: 'December 4, 2017',
    mfg: 'DOVER STREET MARKET Singapore, Singapore',
    featured: 'Editorial, Fashion',
    material: 'Rubber',
    type: 'Velcro',
    price: '2500.00',
  },
  {
    id: 6,
    img: 'https://source.unsplash.com/76w_eDO1u1E/1000x800',
    name: 'Floating nike air jordan 1 mid',
    purchases: '5,823',
    released: 'August 10, 2020',
    mfg: 'Amsterdam, Nederland',
    featured: 'Editorial, Fashion',
    material: 'Rubber',
    type: 'Velcro',
    price: '2500.00',
  },
  {
    id: 7,
    img: 'https://source.unsplash.com/NGWwHZeHNVE/1000x800',
    name: 'Nike Blazer on white background on white desk',
    purchases: '4,240',
    released: 'July 23, 2020',
    mfg: 'NA',
    featured: 'Editorial, Fashion',
    material: 'Rubber',
    type: 'Velcro',
    price: '2500.00',
  },
  {
    id: 8,
    img: 'https://source.unsplash.com/SD9Jyl1xNQ4/1000x800',
    name: 'Nike Air Force',
    purchases: '3,416',
    released: 'September 16, 2020',
    mfg: 'NA',
    featured: 'Editorial, Fashion',
    material: 'Rubber',
    type: 'Velcro',
    price: '2500.00',
  },
  {
    id: 9,
    img: 'https://source.unsplash.com/LV_4qM5Gf9c/1000x800',
    name: 'Nike Air Jordan Pink',
    purchases: '1,081',
    released: 'March 21, 2020',
    mfg: 'NA',
    featured: 'Editorial, Health & Wellness',
    material: 'Rubber',
    type: 'Velcro',
    price: '2500.00',
  },
];
